### ISSUE TITLE
Will I get banned if I use the tool for “The Division”?

### ISSUE THREAD

**Issue by ckx516712534** [Hattiwatti/CinematicTools#3]

**Comment by DaddyWesker** [comment]
Heh, same question =)

**Comment by Trebll** [comment]
> Heh, same question =)

in theory, it should be safe now, I used it about a year or two ago (can't fully remember) and didn't get banned buuut it was only once so id say **use it at your own risk** :)

**Comment by Hattiwatti** [comment]
You might, no guarantees, use at your own risk. I haven't personally heard of anyone getting banned
