### ISSUE TITLE
Cinetools website down?

### ISSUE THREAD

**Issue by Trebll** [Hattiwatti/CinematicTools#8]
I noticed that Cinetools.xyz is dead.
is this a known issue or is it related to something else?

Looking to grab the cinetools for NFS Payback but the website is dead :(
![102700514-e1550c00-4256-11eb-87bd-b9165a38cbfd](https://user-images.githubusercontent.com/76267123/102700537-034e8e80-4257-11eb-993d-5a036a4122f5.png)

**Comment by Cri16228** [comment]
https://web.archive.org/web/*/http://cinetools.xyz/download/CT_NFS17_20180620.zip

**Comment by Nuborka** [comment]
> https://web.archive.org/web/*/http://cinetools.xyz/download/CT_NFS17_20180620.zip or https://web.archive.org/web/20201106200517/http://cinetools.xyz/download/CT_NFS17_20180620.zip

Can I get a download link for the cinetools for NFS Rivals?

**Comment by darderik** [comment]
[CT_MEAndromeda_20180210-44ebd3.zip](https://github.com/Hattiwatti/CinematicTools/files/6306929/CT_MEAndromeda_20180210-44ebd3.zip)
this is andromeda version

**Comment by Trebll** [comment]
Hey there.
If you are looking for cinetools go to the link Matti posted on Twitter

Twitter Post:
https://twitter.com/Hattiwatt1/status/1335289609023086594

or you can go to this link, this Mediafire folder belongs to Matti
if you don't trust me use the one he posted on Twitter :)

Mediafire Folder:
https://www.mediafire.com/folder/tnmqo9becu169/CinematicTools
Password for the archives is "CinematicTools"
