### ISSUE TITLE
Mirror's Edge Catalyst files?

### ISSUE THREAD

**Issue by Jakemakesahub05** [Hattiwatti/CinematicTools#9]
I really wanna try it on Mirror's Edge Catalyst but I can't find the files.

**Comment by Trebll** [comment]
Hey there.
I wrote this in a previous post but If you are looking for cinetools go to the link Matti posted on Twitter

Twitter Post:
https://twitter.com/Hattiwatt1/status/1335289609023086594

or you can go to this link, this Mediafire folder belongs to Matti
if you don't trust me use the one he posted on Twitter :)

Mediafire Folder:
https://www.mediafire.com/folder/tnmqo9becu169/CinematicTools
Password for the archives is "CinematicTools"
